name: causarray
channels:
  - conda-forge
  - defaults
dependencies:  
  - h5py
  - hdf5
  - ipykernel
  - joblib
  - jupyter
  - matplotlib
  - numba
  - numpy
  - pandas
  - pip  
  - python>=3.8
  - scanpy
  - scikit-learn>=1.6
  - scipy
  - seaborn
  - statsmodels>=0.14
  - tqdm

  # for development
  - pytest
  - wheel

  # for documentation
  - sphinx
  - sphinx-book-theme
  - numpydoc
  - nbsphinx # Jupyter to RST
  - sphinxcontrib-bibtex
  - sphinxcontrib-svg2pdfconverter
  - jupyter_contrib_nbextensions
  - myst-parser # Markdown to RST

  - pip:
      - sklearn-ensemble-cv>=0.2.4
      
      # for development
      - build
      - pyproject-hooks
      

